name: Continuous Integration
on:
  # Every push
  push:
  schedule:
    # Every Monday and Thursday at 12PM UTC
    - cron: '0 12 * * 1,4'

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ ^12.17.0, ^13.0.0, ^14.0.0 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: ./node_modules/.bin/c8 --reporter=lcovonly npm test
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
  release-readiness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ^14.0.0
    - run: npm ci
    - run: npm run release-readiness
