name: Continuous Integration
on:
  # Main branch updated
  push:
    branches:
      - main
  # Pull request
  pull_request:
    types:
      # Newly opened
      - opened
      # Updated (excludes change of base branch)
      - synchronize

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ ^14.0.0, ^16.0.0, ^18.0.0 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --ignore-scripts
    - run: ./node_modules/.bin/c8 --reporter=lcovonly npm test
    - uses: codecov/codecov-action@v3.1.1

  pnpm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ^16.0.0
    - uses: actions/cache@v3
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: pnpm-check-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
        restore-keys: pnpm-check-${{ env.cache-name }}-
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: ^7.12.1
        run_install: |
          - args: [--ignore-scripts]
    - run: pnpm run compile
    - run: pnpm test

  release-readiness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ^16.0.0
    - run: npm ci
    - run: npm run release-readiness

  dependabot-approveOrMerge:
    needs: [test, pnpm-check, release-readiness]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Assess changes
      uses: tony84727/changed-file-filter@v0.2.2
      id: filter
      with:
        filters: |
          requirementsChanged:
            - 'package.json'
    - name: Merge lockfile changes
      uses: fastify/github-action-merge-dependabot@v3.5.4
      if: steps.filter.outputs.requirementsChanged == 'false'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Approve requirement changes
      uses: fastify/github-action-merge-dependabot@v3.5.4
      if: steps.filter.outputs.requirementsChanged == 'true'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        approve-only: true
